name: Release
on:
  push:
    branches:
      - 'main'
jobs:
  Release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Prepublish
        run: yarn prepublishOnly
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release -d
